version: '3.7'
services:
  vtigeropensource:
    image: vtigercrm/vtigercrm-8.2.0:latest
    environment:
      mysql_user: ${mysql_user:-admin}
      mysql_pass: ${mysql_pass:-admin}
    ports:
      - target: 80
        published: 80
        mode: host
    volumes:
      - vtiger_source_volume:/var/www/html/
      - vtiger_mysql_data_volume:/var/lib/mysql
volumes:
  vtiger_source_volume:
    driver: local
  vtiger_mysql_data_volume:
    driver: local
