version: '3.7'
services:
  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
    ports:
      - 27017:27017
    networks:
      - mongo_net
    volumes:
      - mongodb_data:/data/db
      - config_mongodb:/data/configdb
    command: mongod --auth --wiredTigerCacheSizeGB 1.5
    restart: unless-stopped

networks:
  mongo_net:

volumes:
  mongodb_data:
    driver: local
  config_mongodb:
    driver: local